version: '3'

services:

  neo4j:
    container_name: motorshop_neo4j
    image: neo4j:4.0.5
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/letmein

  rabbitmq:
    container_name: motorshop_rabbit
    image: rabbitmq:3.8.4-management
    ports:
      - 5672:5672
      - 15672:15672
